### ISSUE TITLE
About window issue

### ISSUE THREAD

**Issue by greenozon** [mrfearless/MediaPlayer#1]
Looks like some paint related issues - it leaves some old windwos instead of repaint, eg:

![image](https://github.com/user-attachments/assets/95ebc749-5358-454f-b496-894827fe4156)

**Comment by mrfearless** [comment]
I think it was returning a NULL_BRUSH in the WM_CTLCOLORSTATIC that is causing that. I will change it to a WHITE_BRUSH, which should fix it i think (i hope)

**Comment by greenozon** [comment]
Thanks, fixed in 1.0.0.1
so closing
