### ISSUE TITLE
ver 1.0.0.3 regression

### ISSUE THREAD

**Issue by greenozon** [mrfearless/MediaPlayer#10]
can't play those mp4 (h624) that 1002 was able to play
crashing right on start...

MediaPlayer.exe
x64

**Comment by greenozon** [comment]
pic from VS - crash dump,..

![image](https://github.com/user-attachments/assets/34b7c388-a648-44bd-ad89-8a4e52462d01)

**Comment by mrfearless** [comment]
I just uploaded a quick update to the MFPlayer-Library that was causing the crash when trying to null out the end of the language for a stream that has lang text in it. I have also recompiled the x64 version as this was the one that was crashing. So in the releases section the newer x64 version has replaced the previous one that was crashing. Let me know how it goes.

**Comment by greenozon** [comment]
Thanks!
just tested out fixed build
regression is gone

**Comment by mrfearless** [comment]
Thanks for testing it, glad to hear that.
