### ISSUE TITLE
Hardcodes PATHs in sources

### ISSUE THREAD

**Issue by greenozon** [mrfearless/MediaPlayer#12]
Is it possible to not use absolute (hardcoded) PATHs in the sources?

for example while browsing asm file I've seen this one:

`;    includelib M:\Masm32\lib\Debug32.lib`
maybe there are more!

thanks

**Comment by mrfearless** [comment]
Thats for me when debugging it. I comment them out when building the release versions. You can ignore them, or modify them if you are building with a debug build.
