### ISSUE TITLE
[idea] Frame step feature

### ISSUE THREAD

**Issue by greenozon** [mrfearless/MediaPlayer#13]
Hi!
Right now the `Frame step` works like a single click - single action
Is it possible to constantly execute this button hander until the button being pressed down?

![image](https://github.com/user-attachments/assets/45610f87-4490-4b0d-a793-46b7c08eaa5f)

once the button pressed up - stop the handler callings...

**Comment by mrfearless** [comment]
I looked at adding this, but it just behaves as if the play rate is x2. It might be possible to add in a timer, but then we are effectively duplicating the play rate that the engine provides. So unfortunately I don't think its something I will add for now.
