### ISSUE TITLE
Unicode file names

### ISSUE THREAD

**Issue by greenozon** [mrfearless/MediaPlayer#2]
The great thing is that movies with Unicode chars in it's filename are playable
but
there are two locations which does not render chars correctly - 
1) Window title
2) MRU list

any ideas if it could be supported?

**Comment by mrfearless** [comment]
I will have a think about it, but no promises ;-)

**Comment by greenozon** [comment]
Unicode support looks good
1) could open up Unicode file name from console as cmd line arg
2) could open up when doing d-n-d unicode named video

Thanks!

![image](https://github.com/user-attachments/assets/e616e5b2-67c9-46d2-8931-87a434bac2d6)
