### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by greenozon** [mrfearless/MediaPlayer#3]
Do you think it'll make the player more user friendly if it'll support media files from the command line?

**Comment by mrfearless** [comment]
It already supports this, you can also right click on a media file in explorer, like say an mp4 and open with, and select the MediaPlayer to open it with (might have to browse to the location, and unselect the set this as default option- let some other media player be the default ;-) )

**Comment by greenozon** [comment]
OK, one important bit missed out - if you try to open up media with unicode chars - nothing happens

**Comment by greenozon** [comment]
related to this issue - https://github.com/mrfearless/MediaPlayer/issues/2

**Comment by greenozon** [comment]
as it was related to Unicode filenames of videos - it was successfully fixed and no issues found (tested both short and absolute (long) pathes
