### ISSUE TITLE
Player got crazy in some cases

### ISSUE THREAD

**Issue by greenozon** [mrfearless/MediaPlayer#6]
it's a bit tricky but I"ll try to describe the steps
- open up short video
- press couple of times the faster play speed button
- press couple of times the step forward 10 seconds button (almost until end of video, but leave some 5-10 seconds)
- the left hand counter will continue counting seconds even after movie duration over!

after that incident the first 7 buttons (3 + 4) start doing nothing
well, they are clickable, but performs 0 actions
the only thing you could do - open up new video (CTRL + O)  BUT IT WILL NOT PLAY!

![image](https://github.com/user-attachments/assets/7e832767-b4d5-435b-a588-e1e79e0af4cb)

PS used build x64 of version 1.0.0.1

**Comment by mrfearless** [comment]
Hopefully this is fixed in the 1.0.0.2 update.

**Comment by greenozon** [comment]
it defintely does!
👍👍👍👍👍
