### ISSUE TITLE
Issue with shortcuts

### ISSUE THREAD

**Issue by greenozon** [mrfearless/MediaPlayer#7]
Open up player (x64, version 1.0.0.1)

![image](https://github.com/user-attachments/assets/9328a7c6-cf9a-4adc-9aaa-d3d2d06ede9f)

press ALT button
you'll start seeing underlined letters on menu
try to use ALT+ F/ ALT +M / ALT +H ->  nothing happens

expected:  shortcut works (triggers menu item handlers)

**Comment by mrfearless** [comment]
Hopefully this is fixed in the 1.0.0.2 update.

**Comment by greenozon** [comment]
absolutely!
👍👍👍
