### ISSUE TITLE
MRU list idea

### ISSUE THREAD

**Issue by greenozon** [mrfearless/MediaPlayer#8]
Hi!
currently I"ve collected some small test set of different videos having different codecs (H.265, H.266, vvc1, av1, etc etc)
of course some are not supported by this player and thats understandable and is absolutely fine (as we blame windows not the player itself!)

but, for some reason the player adds all those "non-playable" videos into the MRU list

do you think it makes sense to not add those "non-playable" ones?

**Comment by mrfearless** [comment]
Its a strange problem with the MFPlay media engine. If it allows the creation of a media item via MFPMediaPlayer_CreateMediaItem (which is a wrapper to the IMFPMediaPlayer:CreateMediaItemFromURL method) then its good to play (or attempt to play), if its not, then it fails - so like trying to open an .exe file for example will fail with that function. Or other formats like .ogg etc. 

The MediaPlayer only adds to the MRU list once the MFPMediaPlayer_CreateMediaItem returns TRUE. Also there is an event notification callback for an error, but I have never seen it send one. So no way to currently check if its one of the non-playable files that I can think of.

Some of the formats/codecs when accepted by the MFPlay media engine seem to kill it when trying to then load another known good one, which is a problem as well, but not one that seems to have a solution. Probably why Microsoft kept evolving the Media Foundation APIs. 

The MFPlay API has the most compatibility with older operating systems, and the simplest COM to implement - which is fine, as I only started learning about it recently. The newer evolution of the Media Foundation seem to have a lot more COM objects and more complexities, but only work on newer versions of windows. But the newer Media Foundation may have more/better features for handling issues and more support for codecs/formats.

**Comment by mrfearless** [comment]
I changed some code to re-initialize the media engine every time a media file is loaded. This partially resolves the issue where a media file with a different codec from the previous one loaded would cause the media player engine to freeze the player rendering and kill the engine. If you loaded say an h.264 file and then another and so on, it appears to work fine. But if you then tried to load a h.265 or wmv or something else then it would crap out. Restarting the engine each time seems to alleviate this.

Now that the engine is restarted each time, I might be able to detect some problem video types that are accepted by the Media Engine but dont actually work, before they are played, and if they are a problem video or codec then I can skip adding it to the MRU list. I will put it on the list of things to look into.

**Comment by mrfearless** [comment]
Closing this one.
